version: '3'
services:
  maze:
    build: /
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://maze_db:3306/maze_game
      DB_USER: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      maze_db:
        condition: service_healthy
  maze_db:
    image: mysql
    container_name: maze_db
    environment:
      MYSQL_DATABASE: 'maze_game'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - maze_db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80    
    volumes:
      - my-db:/var/lib/mysql
      
# Names our volume
volumes:
  my-db: